image:
  repository: 793872273299.dkr.ecr.eu-west-1.amazonaws.com/ecr-alx
  tag: v1.0.1
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: false

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: test_pass

hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70